### PR TITLE
Add switch for autopeering or static neighbors with configuration

### PR DESCRIPTION
**Pull request by 0xKtota**

### CODE REVIEW

**Comment by dlt-green** [comment]
how manage peering partners when autopeering is false?
added cfg update for existing installations
added autopeering to installation info

**Comment by dlt-green** [comment]
readme update open
for me it's of for merge into dev

**Review by dlt-green — APPROVED** [review]

**Comment by fhb191309** [comment]
can we have a short description the next time?

what is flexible autopeering used for ?

**Comment by dlt-green** [comment]
please be part of coming 'Node-Installer-Docker - Training for Collaborators' 26 Feb 2024 21:00 - Rules are discussed there and reviewed and set to public here

**Comment by dlt-green** [comment]
> can we have a short description the next time?
> 
> what is flexible autopeering used for ?

in my opinion it's needed when you want to set up static peers (for the normal user not needed) but in certain cases maybe useful. like i said above, there are some points to clear:
x how manage peering partners when autopeering is false?
x readme is open to change
x what happend to manually added peering partners?
   also available after node update?
   what happens when static peers are in config and when you enable autopeering afterwards?
   
x added some code thats needed to run correct also for nodes, what are already installed

**Review by dlt-green — CHANGES_REQUESTED** [review]
ℹ️questions must be answered to get a review

**Comment by 0xKtota** [comment]
> can we have a short description the next time?
what is flexible autopeering used for ?

Sure👍

Description:
The "flexible autopeering" feature enables Hornet nodes to utilize either automatic peering, manual peering, or both, offering customizable network connectivity options.


> please be part of coming 'Node-Installer-Docker - Training for Collaborators' 26 Feb 2024 21:00 CET - Rules are discussed there and reviewed and set to public here

date saved 📝

> x how manage peering partners when autopeering is false?

With this version via Hornet's dashboard, but I'm currently testing an improved version where you store the static neighbors in the .env to use them for generating the peering.json

> x readme is open to change

Should the information be written into the readme that you can use manual peers in addition to autopeering, or what do you mean? because the fact that you can set PoW, for example, is not listed either

> x what happend to manually added peering partners?
also available after node update?

After an update these might be lost and you would have to add the static peers again, so I'm working on an improved version, which I'll submit shortly.

> what happens when static peers are in config and when you enable autopeering afterwards?

If you have configured static peers and later activate autopeering, the node normally works with a combination of both peering methods.

In some cases, the IF recommends a combination of both peer methods:

"To minimize service distribution in case your autopeered peers are flaky, we recommend you only use autopeering if you have at least four static peers."

https://wiki.iota.org/hornet/references/peering/#autopeering


> x added some code thats needed to run correct also for nodes, what are already installed
x in the future a description is needed and the PR must be squashed before

👍

**Comment by dlt-green** [comment]
thanks for your answers. The question is whether it is enough to be able to change this setting manually via the ENV, or to suggest this setting via the installer during installation. With PoW it was necessary to actively include this as a point due to possible legal problems for the hosts. But you can also change PoW afterwards. maybe only offer the parameter as a setting via the ENV. Most people will use autopeering this way, and so there is no risk of the node not working at all after installation. then we also musst prepare the peering.json to not lose this file. you don't must code this all by your wown, you should disguss this in our x-team before how we maybe solve this!

**Review by dlt-green — APPROVED** [review]
merging into dev ok for further testing, There may be other small things that need to be adjusted. docker adjustments still need to be checked

**Review by bogenlos — APPROVED** [review]

**Review by dlt-green — APPROVED** [review]

**Comment by dlt-green** [comment]
**⌛waiting for review**

**Review by fhb191309 — APPROVED** [review]

**Comment by dlt-green** [comment]
✅external PR accepted (3 approvals necessary | PR getting 3 approvals / no changes requested)
ℹ️will be integrated into the next version after successful testing, there will be maybe some adjustments necessary (dev-branch)
💚thank you for supporting our installer, don't forget to give us a ⭐ if you like it

**Pull request merged**
